# Generated by Django 4.2.4 on 2023-09-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_todolist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='user',
            new_name='user_mail',
        ),
    ]
